_site/play-with-docker/Portus/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

_site/play-with-docker/Portus/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)      default(""), not null
#  email                  :string(255)      default("")
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean          default("0")
#  enabled                :boolean          default("1")
#  ldap_name              :string(255)
#  failed_attempts        :integer          default("0")
#  locked_at              :datetime
#  display_name           :string(255)
#  namespace_id           :integer
#
# Indexes
#
#  index_users_on_display_name          (display_name) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_namespace_id          (namespace_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#

class User < ActiveRecord::Base
  include PublicActivity::Common

  enabled_devise_modules = [:database_authenticatable, :registerable, :lockable,
                            :recoverable, :rememberable, :trackable, :validatable,
                            authentication_keys: [:username]]

  enabled_devise_modules.delete(:validatable) if Portus::LDAP.enabled?
  devise(*enabled_devise_modules)

  APPLICATION_TOKENS_MAX = 5

  # Actions performed before/after create.
  validates :username, presence: true, uniqueness: true
  validate :private_namespace_and_team_available, on: :create
  after_create :create_personal_namespace!

  # Actions performed before destroy
  before_destroy :update_tags!

  belongs_to :namespace
  has_many :team_users
  has_many :teams, through: :team_users
  has_many :stars
  has_many :application_tokens

  scope :not_portus, -> { where.not username: "portus" }
  scope :enabled,    -> { not_portus.where enabled: true }
  scope :admins,     -> { not_portus.where enabled: true, admin: true }

  # Special method used by Devise to require an email on signup. This is always
  # true except for LDAP.
  def email_required?
    !(Portus::LDAP.enabled? && email.blank?)
  end

  # It adds an error if the username clashes with either a namespace or a team.
  def private_namespace_and_team_available
    ns = Namespace.make_valid(username)

    if ns.nil?
      errors.add(:username, "'#{username}' cannot be transformed into a " \
        "valid namespace name")
    elsif Namespace.exists?(name: ns)
      clar = (ns != username) ? " (modified so it's valid)" : ""
      errors.add(:username, "cannot be used: there is already a namespace " \
        "named '#{ns}'#{clar}")
    elsif Team.exists?(name: username)
      errors.add(:username, "cannot be used: there is already a team named " \
        "like this")
    end
  end

  # Returns true if the current user is the Portus user.
  def portus?
    username == "portus"
  end

  # Returns the username to be displayed.
  def display_username
    return username unless APP_CONFIG.enabled?("display_name")
    display_name.blank? ? username : display_name
  end

  # This method will be called automatically once a user is created. It will
  # also be created for each user of the system when a registry is saved in the
  # system.
  def create_personal_namespace!
    # the registry is not configured yet, we cannot create the namespace
    return unless Registry.any?

    # Leave early if the namespace already exists. This is fine because the
    # `private_namespace_and_team_available` method has already checked that
    # the name of the namespace is fine and that it doesn't clash.
    namespace_name = Namespace.make_valid(username)
    ns = Namespace.find_by(name: namespace_name)
    return ns if ns

    # Note that this shouldn't be a problem since the User controller will make
    # sure that we don't create a user that clashes with this team.
    team = Team.create!(name: username, owners: [self], hidden: true)

    default_description = "This personal namespace belongs to #{username}."
    namespace = Namespace.find_or_create_by!(
      team:        team,
      name:        namespace_name,
      visibility:  Namespace.visibilities[:visibility_private],
      description: default_description,
      registry:    Registry.get # TODO: fix once we handle more registries
    )
    update_attributes(namespace: namespace)
  end

  # Find the user that can be guessed from the given push event.
  def self.find_from_event(event)
    actor = User.find_by(username: event["actor"]["name"])
    logger.error "Cannot find user #{event["actor"]["name"]}" if actor.nil?
    actor
  end

  # Toggle the 'admin' attribute for this user. It will also update the
  # registry accordingly.
  def toggle_admin!
    admin = !admin?
    return unless update_attributes(admin: admin) && Registry.any?

    # TODO: fix once we handle more registries
    team = Registry.get.global_namespace.team
    admin ? team.owners << self : team.owners.delete(self)
  end

  ##
  # Enabling/disabling users.

  # Toggle the enabled attribute for a user. This is an instance method because
  # it is a user that enables/disables another user.
  def toggle_enabled!(user)
    enabled = user.enabled?

    # Return false if the action is not allowed.
    return false if enabled && !can_disable?(user)
    return false if !enabled && !admin?

    user.update_attributes(enabled: !enabled)
  end

  # This method is picked up by Devise before signing in a user.
  def active_for_authentication?
    super && enabled?
  end

  # The flashy message to be shown for disabled users that try to login.
  def inactive_message
    "Sorry, this account has been disabled."
  end

  # Returns all users who match the query.
  def self.search_from_query(members, query)
    enabled.where.not(id: members).where(arel_table[:username].matches(query))
  end

  # Looks for an application token that matches with the plain one provided
  # as parameter.
  # Return true if there's an application token matching it, false otherwise
  def application_token_valid?(plain_token)
    application_tokens.each do |t|
      if t.token_hash == BCrypt::Engine.hash_secret(plain_token, t.token_salt)
        return true
      end
    end

    false
  end

  # Update the tags owned by this user before this user gets destroyed.
  def update_tags!
    Tag.where(user_id: id).update_all(user_id: nil, username: username)
  end

  # Update the activities owned by this user. This method should only be called
  # before destroying this user.
  def update_activities!(owner)
    # Originally this was handled in a single query, but with that is was not
    # possible to fix a bug as specified in PR #1144. Now it's handled in a
    # block that ends up performing multiple queries, which we want to perform
    # atomically (thus the transaction).
    ActiveRecord::Base.transaction do
      PublicActivity::Activity.where(owner_id: id).find_each do |a|
        a.owner_id   = nil
        a.owner_type = nil
        a.parameters = a.parameters.merge(owner_name: display_username)
        a.save
      end
    end

    create_activity :delete,
                    owner:      owner,
                    parameters: { username: username }
  end

  protected

  # Returns whether the given user can be disabled or not. The following rules
  # apply:
  #   1. A user can disable himself unless it's the last admin on the system.
  #   2. The admin user is the only one that can disable other users.
  def can_disable?(user)
    # The "portus" user can never be disabled.
    return false if user.portus?

    if self == user
      # An admin cannot disable himself if he's the only admin in the system.
      # Otherwise, regular users can disable themselves.
      return true unless admin?
      User.admins.count > 1
    else
      # Only admin users can disable other users.
      admin?
    end
  end
end

_site/play-with-docker/Portus/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  respond_to :html, :js
  before_action :another_user_access, only: [:edit, :update, :destroy]

  def index
    @users = User.not_portus.order(:username).page(params[:page])
    @admin_count = User.admins.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_create_params)

    if @user.persisted?
      flash[:notice] = "User '#{@user.username}' was created successfully"
      flash[:float] = true
      redirect_to admin_users_path
    else
      flash[:alert] = @user.errors.full_messages
      flash[:float] = true
      render "new"
    end
  end

  # GET /admin/user/1/edit
  def edit
  end

  # PATCH/PUT /admin/user/1
  def update
    return if @user.nil?

    attr = params.require(:user).permit([:email, :display_name])

    if @user.update_attributes(attr)
      redirect_to admin_users_path,
                  notice: "User '#{@user.username}' was updated successfully",
                  float:  true
    else
      redirect_to edit_admin_user_path(@user),
                  alert: @user.errors.full_messages,
                  float: true
    end
  end

  # DELETE /admin/user/:id
  def destroy
    return if @user.nil?

    @user.update_activities!(current_user)
    @user.destroy!

    redirect_to admin_users_path,
                notice: "User '#{@user.username}' was removed successfully",
                float:  true
  end

  # PATCH/PUT /admin/user/1/toggle_admin
  def toggle_admin
    user = User.find(params[:id])

    if user == current_user
      render nothing: true, status: 403
    else
      user.toggle_admin!
      render template: "admin/users/toggle_admin", locals: { user: user }
    end
  end

  private

  def user_create_params
    permitted = [:username, :email, :password, :password_confirmation]
    params.require(:user).permit(permitted)
  end

  # Sets the @user instance variable if the current user is different from the
  # one specified in params[:id]. Moreover, if the current user is the same as
  # the targeted one, then a 403 response is rendered.
  def another_user_access
    @user = User.find(params[:id])
    return if !@user.nil? && @user != current_user

    @user = nil
    render nothing: true, status: 403
  end
end

_site/play-with-docker/Portus/app/views/admin/users/edit.html.slim
.panel.panel-default
  .panel-heading
    h5 <b>Edit</b> #{@user.display_username}
  .panel-body
    = form_for [:admin, @user], html: {class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :email, {class: 'control-label col-md-2'}
        .col-md-7
          = f.email_field(:email, class: 'form-control', required: true, autofocus: true)

      - if APP_CONFIG.enabled?("display_name")
        .form-group
          = f.label :display_name, {class: 'control-label col-md-2'}
          .col-md-7
            = f.text_field(:display_name, class: 'form-control')

      .form-group
        .col-md-offset-2.col-md-7
          = f.submit('Update', class: 'btn btn-primary')

.panel.panel-default
  .panel-heading
    h5 <b>Remove</b> #{@user.display_username}
  .panel-body
    = form_for @user, url: admin_user_path(@user), method: :delete, html: {id: "delete_user_#{@user.id}", class: 'form-horizontal', role: "form"} do |f|
      .form-group
        .col-md-offset-2.col-md-7
          p
            | As an administrator, you can remove this user. That being said, be aware that doing this has its consequences:
          ul
            li
              | The namespace and the repositories of this user won't be removed. You will still be able to access them and manage them.
            li
              | The user will be lost forever, so you won't be able to recover the data.
          p
            | With this in mind, if you want to remove this user, just click the button below.
      .form-group
        .col-md-offset-2.col-md-7
          = f.submit('Remove', class: 'btn btn-danger')

_site/play-with-docker/Portus/app/views/admin/users/index.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-sm-6
        h5
          ' Registered users
      .col-sm-6.text-right
        = link_to new_admin_user_path, class: 'btn btn-xs btn-link', role: 'button'
          i.fa.fa-plus-circle
          | Create new user
  .panel-body
    .table-responsive
      table.table.table-stripped.table-hover
        col.col-20
        col.col-30
        col.col-10
        col.col-10
        col.col-10
        col.col-10
        col.col-10
        thead
          tr
            th Name
            th Email
            th Admin
            th Namespaces
            th Teams
            th Enabled
            th Remove
        tbody
          - @users.each do |user|
            tr[id="user_#{user.id}"]
              - if user == current_user
                td= user.display_username
              - else
                td
                  = link_to user.display_username, edit_admin_user_path(user), { title: "Edit user '#{user.display_username}'" }
              td= user.email
              td.admin-btn
                - if current_user.id == user.id
                  i.fa.fa-lg[class="fa-toggle-#{user.admin? ? 'on': 'off'}"]
                - else
                  a[class="btn btn-default"
                    data-remote="true"
                    data-method="put"
                    rel="nofollow"
                    href=url_for(toggle_admin_admin_user_path(user))]
                      i.fa.fa-lg[class="fa-toggle-#{user.admin? ? 'on': 'off'}"]

              td= user.teams.reduce(0) { |sum, t| sum += t.namespaces.count}
              td= user.teams.all_non_special.count
              td.enabled-btn
                - if current_user.id == user.id && @admin_count == 1
                  i.fa.fa-lg.fa-toggle-on
                - else
                  a[class="btn btn-default"
                    data-remote="true"
                    data-method="put"
                    rel="nofollow"
                    href=url_for(toggle_enabled_path(user))]
                      i.fa.fa-lg[class="fa-toggle-#{user.enabled? ? 'on': 'off'}"]
              td.remove-btn
                - if current_user == user
                    a[class="btn btn-default" disabled=true]
                      i.fa.fa-trash.fa-lg
                - else
                    a[class="btn btn-default"
                        data-placement="left"
                        data-toggle="popover"
                        data-title="Please confirm"
                        data-content='<p>Are you sure you want to remove this user?</p><a class="btn btn-default">No</a> <a class="btn btn-primary btn-confirm-remove" data-method="delete" rel="nofollow" href="#{admin_user_path(user)}">Yes</a>'
                        data-html="true"
                        tabindex="0"
                        role="button"
                    ]
                      i.fa.fa-trash.fa-lg
  .panel-footer= paginate(@users)

_site/play-with-docker/Portus/app/views/admin/users/new.html.slim
.panel.panel-default
  .panel-heading
    h5 New User
  .panel-body
    = form_for [:admin, @user], html: {class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :username, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:username, class: 'form-control', required: true, autofocus: true)
      .form-group
        = f.label :email, {class: 'control-label col-md-2'}
        .col-md-7
          = f.email_field(:email, class: 'form-control', required: true)
      .form-group
        = f.label :password, {class: 'control-label col-md-2'}
        .col-md-7
          = f.password_field(:password, class: 'form-control', required: true)
      .form-group
        = f.label :password_confirmation, {class: 'control-label col-md-2'}
        .col-md-7
          = f.password_field(:password_confirmation, class: 'form-control', required: true)

      .form-group
        .col-md-offset-2.col-md-7
          = f.submit('Create', class: 'btn btn-primary')

_site/play-with-docker/Portus/app/views/admin/users/toggle_admin.js.erb
$('#user_<%= user.id %> .admin-btn a i').addClass("fa-toggle-<%= user.admin? ? 'on' : 'off' %>");
$('#user_<%= user.id %> .admin-btn a i').removeClass("fa-toggle-<%= user.admin? ? 'off' : 'on' %>");

$('#float-alert p').html("User '<%= user.username %>' is <%= user.admin? ? 'now' : 'no longer' %> an admin");
$('#float-alert').fadeIn(setTimeOutAlertDelay());